### ISSUE TITLE
Pre-trained Text Tokenizer

### ISSUE THREAD

**Issue by langong347** [mugen-org/MUGEN_baseline#3]
From `README.md`, looks like we will need to download the coinrun dataset and run the [training script](https://github.com/mugen-org/MUGEN_baseline/blob/main/generation/train_tokenizer.py) to generate the tokenizer file.

I am wondering if you also provide pre-trained file that we can directly plug into the GPT module?

Thank you!

**Comment by Sy-Zhang** [comment]
> From `README.md`, looks like we will need to download the coinrun dataset and run the [training script](https://github.com/mugen-org/MUGEN_baseline/blob/main/generation/train_tokenizer.py) to generate the tokenizer file.
> 
> I am wondering if you also provide pre-trained file that we can directly plug into the GPT module?
> 
> Thank you!

The pre-trained tokenizer file is within coinrun.zip. You can  find it in coinrun/tokenizers/ repo.

**Comment by langong347** [comment]
Thank you for the reply. I did see a tokenizer file `tokenizers/tokenizer-coinrun_1024.json` after unzipping. But the extraction took more than 8 hours that I'm not sure if the file is complete (only 24KB now) due to intermittent disconnection. 

Do you know approximately the correct size for the tokenizer file? Is it expected to take that long to unzip?

**Comment by Sy-Zhang** [comment]
> Thank you for the reply. I did see a tokenizer file `tokenizers/tokenizer-coinrun_1024.json` after unzipping. But the extraction took more than 8 hours that I'm not sure if the file is complete (only 24KB now) due to intermittent disconnection.
> 
> Do you know approximately the correct size for the tokenizer file? Is it expected to take that long to unzip?

The size is correct. And yes, most of them are small files, thus it take a long time to unzip all of them.

**Comment by langong347** [comment]
Got it! Thanks. I am able to load the tokenizer now.
