### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by xiaoqian-shen** [mugen-org/MUGEN_baseline#6]
Hi, great work! Thanks for your efforts on such a fine-grained large-scale dataset. I am wondering what is the GPU consumption and training time for 3D VQ-VAE and transformer.

**Comment by Sy-Zhang** [comment]
> Hi, great work! Thanks for your efforts on such a fine-grained large-scale dataset. I am wondering what is the GPU consumption and training time for 3D VQ-VAE and transformer.

All models are trained on a single node with 8xV100. 3D VQ-VAE will cost 1 week for training and the transformer will cost 2-4 days depending on the task.

**Comment by cvpr2023-MoStGAN** [comment]
Thanks for your reply!
